# Generated by Django 3.2 on 2022-04-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_url',
            new_name='post_image_url',
        ),
    ]
