# Generated by Django 3.2 on 2022-04-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_image_url_post_post_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image_url',
        ),
    ]
