# Generated by Django 3.2 on 2022-04-13 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220412_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='all_reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='products.productreview'),
        ),
    ]
